### ISSUE TITLE
Entries without a link

### ISSUE THREAD

**Issue by i0rek** [hashicorp/go-changelog#3]
We are starting to use `go-changelog` for Consul and there is an edgecase that I would like to solve. For changes in Consul Enterprise we don't have a PR or issue that we could link to because this repository is private. Now I am trying to find a way to generate changelog entries without a link to a PR or issue. 

Our current note template:

```
{{- define "note" -}}
{{.Body}} [[GH-{{- .Issue -}}](https://github.com/hashicorp/consul/issues/{{- .Issue -}})]
{{- end -}}
```

I would like it to look like this:

```
{{- define "note" -}}
{{.Body}}{{if .Link}} [[GH-{{- .Issue -}}](https://github.com/hashicorp/consul/issues/{{- .Issue -}})]{{end}}
{{- end -}}
```

Displaying links should be the default, you would want to opt out manually, maybe like this:

~~~
```release-note:enhancement:no-link
Added the `bar` interface.
```
~~~

What do you think about that?

**Comment by paddycarver** [comment]
Hmm. The multiple `:` in the codeblock type feels dangerous to me, and I _think_ I'd like to avoid overloading that.

Considering these changelog entry files need to be named _something_ anyways, and the implication for this name is that it _won't_ be used as a link (which differs from other names), how would you feel about a convention that files with a named prefixed with `.` or `_` or something don't generate links in the changelog? Then your template code could work as written, or with minor tweaking to detect the prefix.

**Comment by i0rek** [comment]
@paddycarver I haven't considered changes to the filename, but I like that.

Just to be clear, a file named `.1234.txt` with this content wouldn't generate a link:

~~~
```release-note:enhancement
Added the `bar` interface.
```
~~~

**Comment by paddycarver** [comment]
Yeah, that's essentially what I'm propoosing. Technically, I think the only change we'd _really_ need to make would be making `strings.HasPrefix` available from the template, then the template could look like this:

```
{{- define "note" -}}
{{.Body}}{{if not stringHasPrefix .Issue "."}} [[GH-{{- .Issue -}}](https://github.com/hashicorp/consul/issues/{{- .Issue -}})]{{end}}
{{- end -}}
```

That way each repo can set its own convention, if they need issues that begin with `.` for whatever reason.
